# Generated by Django 3.2.16 on 2022-12-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(help_text='введите ваше описание поста', verbose_name='Описание')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('photo', models.ImageField(help_text='загрузите картинку', null=True, upload_to='uploads/preview/%Y/%m', verbose_name='Картинка')),
                ('animal_type', models.PositiveSmallIntegerField(choices=[(1, 'Кошка'), (2, 'Собака'), (3, 'Другое')], default=3, verbose_name='Тип животного')),
                ('user', models.ForeignKey(help_text='выберете пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пост', to='posts.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный пост',
                'verbose_name_plural': 'Избранные посты',
            },
        ),
    ]
