# Generated by Django 3.2.16 on 2022-12-13 18:17

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('text', tinymce.models.HTMLField(help_text='введите ваше описание поста', verbose_name='описание')),
                ('photo', models.ImageField(help_text='загрузите картинку', upload_to='uploads/preview/%Y/%m', verbose_name='картинка')),
                ('map_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('map_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_favourites', models.BooleanField(default=False, verbose_name='в избранном')),
                ('user', models.ForeignKey(help_text='выберете пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'превью поста',
                'verbose_name_plural': 'превьюшки постов',
            },
        ),
    ]
