# Generated by Django 3.2.16 on 2022-12-15 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(help_text='введите ваше описание поста', verbose_name='Описание')),
                ('photo', models.ImageField(help_text='загрузите картинку', upload_to='uploads/preview/%Y/%m', verbose_name='Картинка')),
                ('map_long', models.DecimalField(blank=True, decimal_places=6, default=59.0, max_digits=9, null=True)),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, default=59.0, max_digits=9, null=True)),
                ('is_favourites', models.BooleanField(default=False, verbose_name='в избранном')),
                ('user', models.ForeignKey(help_text='выберете пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
