# Generated by Django 3.2.16 on 2022-12-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Пост активен или на паузе'),
        ),
    ]
