# Generated by Django 3.2.16 on 2022-12-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_favourites',
        ),
        migrations.AddField(
            model_name='posts',
            name='animal_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Кошка'), (2, 'Собака'), (3, 'Другое')], default=3, verbose_name='Тип животного'),
        ),
    ]
