# Generated by Django 3.2.16 on 2022-12-14 18:25

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='map_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=59.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='posts',
            name='map_long',
            field=models.DecimalField(blank=True, decimal_places=6, default=59.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='posts',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(help_text='загрузите картинку', upload_to='uploads/preview/%Y/%m', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=tinymce.models.HTMLField(help_text='введите ваше описание поста', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(help_text='выберете пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
