# Generated by Django 3.2.16 on 2022-12-23 14:39

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_posts_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name': 'избранный пост', 'verbose_name_plural': 'избранные посты'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.AlterField(
            model_name='favourites',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='пост', to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='пользователь', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='animal_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Кошка'), (2, 'Собака'), (3, 'Другое')], default=3, verbose_name='тип животного'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(help_text='загрузите картинку', null=True, upload_to='uploads/preview/%Y/%m', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.BooleanField(choices=[(True, 'Пост активен'), (False, 'Пост приостановлен')], default=True, verbose_name='статус поста'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=tinymce.models.HTMLField(help_text='введите ваше описание поста', verbose_name='описание'),
        ),
    ]
