# Generated by Django 3.2.16 on 2022-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221214_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='map_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=59.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='map_long',
            field=models.DecimalField(blank=True, decimal_places=6, default=59.0, max_digits=9, null=True),
        ),
    ]
