# Generated by Django 3.2.16 on 2022-12-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221216_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name': 'Избранный пост', 'verbose_name_plural': 'Избранные посты'},
        ),
        migrations.RenameField(
            model_name='favourites',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='favourites',
            old_name='user_id',
            new_name='user',
        ),
    ]
