# Generated by Django 3.2.16 on 2022-12-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221223_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Серая'), (2, 'Чёрная'), (3, 'Белая')], default=1, verbose_name='цвет животного'),
        ),
    ]
