# Generated by Django 3.2.16 on 2022-12-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20221216_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Возраст'),
        ),
    ]
