# Generated by Django 3.2.16 on 2022-12-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_posts_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='age',
            field=models.PositiveSmallIntegerField(choices=[(1, 'до 1 года'), (2, 'от 1 до 2 лет'), (3, 'от 2 до 5 лет'), (4, 'от 5 до 8 лет'), (5, 'от 8-11 лет'), (6, 'свыше 11 лет'), (100, '---')], default=100, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='cat_breed',
            field=models.PositiveSmallIntegerField(choices=[(2, 'белый'), (3, 'серый'), (4, 'рыжий'), (5, 'черный'), (6, 'черепаховый'), (7, 'трехцветный'), (8, 'бело-черный'), (9, 'бело-рыжий'), (10, 'бело-серый'), (11, 'рыже-черный'), (100, '---')], default=100, verbose_name='порода кошки'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='cat_color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'белый'), (2, 'серый'), (3, 'рыжий'), (4, 'черный'), (5, 'черепаховый'), (6, 'трехцветный'), (7, 'бело-черный'), (8, 'бело-рыжий'), (9, 'бело-серый'), (10, 'рыже-черный'), (100, '---')], default=100, verbose_name='цвет кошки'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='dog_color',
            field=models.PositiveSmallIntegerField(choices=[(2, 'белый'), (3, 'серый'), (4, 'рыжий'), (5, 'черный'), (6, 'черепаховый'), (7, 'трехцветный'), (8, 'бело-черный'), (9, 'бело-рыжий'), (10, 'бело-серый'), (11, 'рыже-черный'), (100, '---')], default=100, verbose_name='цвет собаки'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'мужской'), (2, 'женский'), (100, '---')], default=100, verbose_name='пол животного'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='health',
            field=models.PositiveSmallIntegerField(choices=[(1, 'без особенностей'), (2, 'с особенностями'), (100, '---')], default=100, verbose_name='состояние здоровья'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='other_animal_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'хомяк'), (2, 'кролик'), (3, 'морская свинка'), (4, 'птицы'), (5, 'змеи'), (100, '---')], default=100, verbose_name='тип животного'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(1, 'мелкий'), (2, 'средний'), (3, 'крупный'), (100, '---')], default=100, verbose_name='размер животного'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='socialization',
            field=models.PositiveSmallIntegerField(choices=[(1, 'высокая'), (2, 'средняя'), (3, 'низкая'), (100, '---')], default=100, verbose_name='уровень социализации'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='wool_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'короткошерстная'), (3, 'среднешерстная'), (2, 'длинношерстная'), (100, '---')], default=100, verbose_name='тип шерсти'),
        ),
    ]
