# Generated by Django 3.2.16 on 2022-12-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20221230_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='cat_breed',
            field=models.PositiveSmallIntegerField(choices=[(1, 'породистый'), (2, 'без породы'), (100, '---')], default=100, verbose_name='порода кошки'),
        ),
    ]
