# Generated by Django 3.2.16 on 2022-12-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20221230_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='gallery',
            field=models.FileField(blank=True, null=True, upload_to='uploads/gallery/%Y/%m'),
        ),
    ]
