# Generated by Django 3.2.16 on 2022-12-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='other/img/default_avatar.jpg', help_text='загрузите картинку', upload_to='uploads/avatars/%Y/%m', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_shelter',
            field=models.BooleanField(choices=[(False, 'Пользователь'), (True, 'Приют')], default=False, verbose_name='Приют или посетитель'),
        ),
    ]
