# Generated by Django 3.2.16 on 2022-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221218_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', help_text='загрузите картинку', upload_to='uploads/avatars/%Y/%m', verbose_name='Аватар'),
        ),
    ]
