# Generated by Django 3.2.16 on 2022-12-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(default='ваша информация о приюте', verbose_name='о приюте'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', help_text='загрузите картинку', upload_to='uploads/avatars/%Y/%m', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_shelter',
            field=models.BooleanField(choices=[(False, 'Пользователь'), (True, 'Приют')], default=False, verbose_name='приют или посетитель'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='имя пользователя'),
        ),
    ]
