# Generated by Django 3.2.16 on 2022-12-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Пермь', max_length=150, verbose_name='city'),
        ),
    ]
