# Generated by Django 3.2.16 on 2022-12-21 15:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221221_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(default='ваша информация о приюте', verbose_name='О приюте'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='ваш адресс', max_length=100, verbose_name='адрес приюта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
